// console.log('this is  practice line and linee number 1 which s a print statement')
// console.log('100+10' + '=' + 100+10)
// console.log('100-10' + '=' + (100-10))
// console.log('100*10' + '=' + 100*10)
// console.log('100/10' + '=' + 100/10)
// console.log('100%10' + '=' + 100%10)
// console.log('100**10' + '=' + 100**10)

// const a = prompt('a=?')
// const b = prompt('b=?')
// console.log('a+b' + '=' + (a+b))
// console.log('a-b' + '=' + (a-b))
// console.log('a*b' + '=' + (a*b))

// console.log(typeof "abhishek")
// console.log(typeof 123)
// console.log(typeof true)
// console.log(typeof null)
// console.log(typeof undefined)
// console.log(typeof NaN)
// console.log(typeof Symbol('a'))
// console.log(typeof function(){})

// console.log(parseInt("2004abhi"));

// let user_name = prompt("name")
// let age = prompt("age")
// let city = prompt("city")
// let country = prompt("country")
// let gender = prompt("gender")
// let hobby = prompt("hobby")
// let email = prompt("email")
// let phone = prompt("phone")
// let address = prompt("address")
// console.log(user_name,age,city,country,gender,hobby,email,phone,address)

// const dayInWeek = 7
// console.log(dayInWeek)

// let user_name = ("Abhishek")
// let age = ("21")
// let city = ("Kanpur")
// let country = ("India")
// let gender = ("Male")
// let hobby = ("Playing")
// let email = ("abhisheksharma12891@gmail.com")
// let phone = ("8532955211")
// let address = ("Hanuman Gali")
// console.log(user_name,age,city,country,gender,hobby,email,phone,address)

// var user_name = ("Abhishek")
// var age = ("21")
// var city = ("Kanpur")
// var country = ("India")
// var gender = ("Male")
// var hobby = ("Playing")
// var email = ("abhisheksharma12891@gmail.com")
// var phone = ("8532955211")
// var address = ("Hanuman Gali")
// console.log(user_name,age,city,country,gender,hobby,email,phone,address)

// const user_name = ("Abhishek")
// const age = ("21")
// const city = ("Kanpur")
// const country = ("India")
// const gender = ("Male")
// const hobby = ("Playing")
// const email = ("abhisheksharma12891@gmail.com")
// const phone = ("8532955211")
// const address = ("Hanuman Gali")
// console.log(user_name,age,city,country,gender,hobby,email,phone,address)

